projects:
  BeerSharerUserAPI:
    schemaPath: src/App/graphQlUtils/schema.json
    includes:
      - src/App/graphQlUtils/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: acbdyf4qwbdfxhd4v5jk53unbe
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/App/graphQlUtils
        region: us-east-1
        maxDepth: 2
      endpoints:
        prod: >-
          https://xloqq3d6efguxa7kdpfyqhgsle.appsync-api.us-east-1.amazonaws.com/graphql
