// Login
export const LOGIN_INFO_UPDATE = 'LOGIN_INFO_UPDATE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

// Friend Add
export const FRIEND_CREATE = 'FRIEND_CREATE';
export const FRIENDS_FETCH = 'FRIENDS_FETCH';
export const FRIENDS_FETCH_SUCCESS = 'FRIENDS_FETCH_SUCCESS';
export const FRIEND_UPDATE = 'FRIEND_UPDATE';
