// Login
export const LOGIN_INFO_UPDATE = 'LOGIN_INFO_UPDATE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REACH_MAIN_APP_SUCCESS = 'REACH_MAIN_APP_SUCCESS';

// Friend Add
export const FRIEND_CREATE = 'FRIEND_CREATE';
export const FRIEND_DELETE = 'FRIEND_DELETE';
export const FRIEND_SAVE = 'FRIEND_SAVE';
export const FRIENDS_FETCH = 'FRIENDS_FETCH';
export const FRIENDS_FETCH_SUCCESS = 'FRIENDS_FETCH_SUCCESS';
export const FRIEND_UPDATE = 'FRIEND_UPDATE';
