// Auth
export const APP_INIT_REQUEST = 'APP_INIT_REQUEST';
export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS';
export const LOGIN_INFO_UPDATE = 'LOGIN_INFO_UPDATE';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SIGN_OUT_USER_FAIL = 'SIGN_OUT_USER_FAIL';
export const SIGN_OUT_USER_REQUEST = 'SIGN_OUT_USER_REQUEST';
export const SIGN_UP_INFO_UPDATE = 'SIGN_UP_INFO_UPDATE';
export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';

// Beer
export const BEER_CREATE = 'BEER_CREATE';
export const BEER_DELETE = 'BEER_DELETE';
export const BEER_SAVE = 'BEER_SAVE';
export const BEER_FETCH = 'BEERS_FETCH';
export const BEER_FETCH_SUCCESS = 'BEERS_FETCH_SUCCESS';
export const BEER_UPDATE = 'BEER_UPDATE';

// Friend
export const FRIEND_ADD_FAIL = 'FRIEND_ADD_FAIL';
export const FRIEND_ADD_REQUEST = 'FRIEND_ADD_REQUEST';
export const FRIEND_ADD_SUCCESS = 'FRIEND_ADD_SUCCESS';
export const FRIEND_ADD_DIALOG_CLOSE = 'FRIEND_ADD_DIALOG_CLOSE';
export const FRIEND_ADD_DIALOG_OPEN = 'FRIEND_ADD_DIALOG_OPEN';
export const FRIEND_FETCH_REQUEST = 'FRIEND_FETCH_REQUEST';
export const FRIEND_FETCH_SUCCESS = 'FRIEND_FETCH_SUCCESS';
export const FRIEND_SEARCH_FAIL = 'FRIEND_SEARCH_FAIL';
export const FRIEND_SEARCH_INFO_UPDATE = 'FRIEND_SEARCH_INFO_UPDATE';
export const FRIEND_SEARCH_REQUEST = 'FRIEND_SEARCH_REQUEST';
export const FRIEND_SEARCH_SUCCESS = 'FRIEND_SEARCH_SUCCESS';
export const FRIEND_SELECT = 'FRIEND_SELECT';
