// Auth
export const LOGIN_INFO_UPDATE = 'LOGIN_INFO_UPDATE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REACH_MAIN_APP_SUCCESS = 'REACH_MAIN_APP_SUCCESS';
export const SIGN_OUT_USER_FAIL = 'SIGN_OUT_USER_FAIL';
export const SIGN_UP_INFO_UPDATE = 'SIGN_UP_INFO_UPDATE';
export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';

// Beer
export const BEER_CREATE = 'BEER_CREATE';
export const BEER_DELETE = 'BEER_DELETE';
export const BEER_SAVE = 'BEER_SAVE';
export const BEER_FETCH = 'BEERS_FETCH';
export const BEER_FETCH_SUCCESS = 'BEERS_FETCH_SUCCESS';
export const BEER_UPDATE = 'BEER_UPDATE';

// Friend
export const FRIEND_ADD_DIALOG_CLOSE = 'FRIEND_ADD_DIALOG_CLOSE';
export const FRIEND_ADD_DIALOG_OPEN = 'FRIEND_ADD_DIALOG_OPEN';
export const FRIEND_FETCH = 'FRIEND_FETCH';
export const FRIEND_FETCH_SUCCESS = 'FRIEND_FETCH_SUCCESS';
export const FRIEND_SEARCH_INFO_UPDATE = 'FRIEND_SEARCH_INFO_UPDATE';
